version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./docker/entrypoint.sh:/usr/local/bin/entrypoint
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: news_db
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - news_network
    depends_on:
      - db
    command: ["/usr/local/bin/entrypoint"]
    #command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  db:
    image: mysql:8.0
    container_name: news_db
    restart: always
    environment:
      MYSQL_DATABASE: news_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: news_user
    ports:
        - 3306:3306
    expose:
        - 3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - news_network

  vite:
    image: node:18
    container_name: vite
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    command: ["sh", "-c", "npm install && npm run dev"]

  # nginx:
  #   image: nginx:alpine
  #   container_name: news_nginx
  #   restart: unless-stopped
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./:/var/www
  #     - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - news_network
  #   depends_on:
  #     - app

networks:
  news_network:
    driver: bridge

volumes:
  dbdata: